### PR TITLE
Added user file with username, first name, and surname

### PR DESCRIPTION
**Pull request by ZHANG-png-png**

### CODE REVIEW

**Review by racousin — CHANGES_REQUESTED** [review]
The user file should be in folder ZHANG-png-png/ and sub folder module1/ and not at root level. Path should be data_science_practice_2024/ZHANG-png-png/module1/user

**Review by manjotgeek17 — APPROVED** [review]

**Review by racousin — APPROVED** [review]
Good work!

BTW: you own a review for all this people!

image

**Comment by racousin** [comment]
Merge it or close it!

**Comment by racousin** [comment]
I'm closing this PR because no change for a very long time.

**Pull request closed without merging**
